version: '3'

tasks:
  helm-repo-add:
    cmds:
      - helm repo add eks https://aws.github.io/eks-charts
      - helm repo update
  
  create-argocd-applications:
    cmds:
    - |
      set -e
      for file in deployments/argocd/*; do
        kubectl apply -f $file
      done
  
  apply-infrastructure:
    vars:
      ENV: '{{ .ENV | default "dev" }}'
      COMMAND: '{{ .COMMAND | default "apply" }}'
    cmds:
      - terragrunt run-all --terragrunt-working-dir=infrastructure/envs/{{ .ENV }} {{ .COMMAND }}
    deps:
      - helm-repo-add
  
  argocd-password:
    cmds:
      - terragrunt output -json -terragrunt-working-dir=infrastructure/envs/dev/eks-addons