apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/benjefferies/devops-aws-eks-best-practices-example.git
    targetRevision: main
    path: deployments/dev/backend

  project: my-project

  destination:
    server: https://kubernetes.default.svc
    namespace: my-project

  syncPolicy:
    syncOptions:
      - CreateNamespace=true