name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the backend
      run: docker build apps/backend --file apps/backend/Dockerfile --tag backend
      
    - name: Build the frontend
      run: docker build apps/frontend --file apps/frontend/Dockerfile --tag frontend
