# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "devops-aws-eks-dev-terraform-state"
    dynamodb_table = "devops-aws-eks-dev-terraform-state-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "my-project-dev"
    region         = "eu-west-1"
  }
}
